language: node_js
node_js: stable

branches:
  only:
  - source

install:
- npm install hexo --save
- npm update

script:
- hexo clean
- hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  committer-from-gh: true
  local-dir: public
  target-branch: gh-pages
  on:
    branch: source

notifications:
  email:
    recipients:
      - CaptainYukinoshitaHachiman@ProtonMail.com
    on_success: always
    on_failure: always
